
Currently Loaded Modules:
  1) miniconda/4.9.2   3) cuDNN/7-CUDA-9.0.176
  2) CUDA/9.0.176      4) anaconda/2021-03-tf2

 

Traceback (most recent call last):
  File "/home/moisioa3/.local/bin/mlm", line 33, in <module>
    sys.exit(load_entry_point('mlm', 'console_scripts', 'mlm')())
  File "/home/moisioa3/.local/bin/mlm", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/share/apps/anaconda-ci/fgci-centos7-anaconda/software/miniconda/4.9.2/f625fd92/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/share/apps/anaconda-ci/fgci-centos7-anaconda/software/miniconda/4.9.2/f625fd92/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/scratch/work/moisioa3/conv_lm/mlm-scoring/src/mlm/cmds.py", line 13, in <module>
    import gluonnlp as nlp
  File "/home/moisioa3/.local/lib/python3.8/site-packages/gluonnlp/__init__.py", line 23, in <module>
    from . import loss
  File "/home/moisioa3/.local/lib/python3.8/site-packages/gluonnlp/loss/__init__.py", line 23, in <module>
    from .activation_regularizer import *
  File "/home/moisioa3/.local/lib/python3.8/site-packages/gluonnlp/loss/activation_regularizer.py", line 25, in <module>
    from mxnet.gluon.loss import Loss
  File "/home/moisioa3/.local/lib/python3.8/site-packages/mxnet/__init__.py", line 23, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/home/moisioa3/.local/lib/python3.8/site-packages/mxnet/context.py", line 23, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/home/moisioa3/.local/lib/python3.8/site-packages/mxnet/base.py", line 351, in <module>
    _LIB = _load_lib()
  File "/home/moisioa3/.local/lib/python3.8/site-packages/mxnet/base.py", line 342, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/share/apps/anaconda-ci/fgci-centos7-anaconda/software/miniconda/4.9.2/f625fd92/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudnn.so.8: cannot open shared object file: No such file or directory
